# Generated by Django 5.1.7 on 2025-03-30 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category_categorylink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylink',
            name='catergory',
        ),
        migrations.AddField(
            model_name='categorylink',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorylink', to='posts.category'),
        ),
    ]
