# Generated by Django 5.1.7 on 2025-04-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_categorylink_catergory_categorylink_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylink',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorylink',
            name='post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryLink',
        ),
    ]
